version: "3"
services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: s3c4Et
    volumes:
      - "$PWD/docker/postgres:/docker-entrypoint-initdb.d"
  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    ports:
      - 8082:8080
    environment:
      ADMINER_DESIGN: dracula